# Generated by Django 3.1.1 on 2020-09-16 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(default='compta', max_length=200, unique=True)),
                ('decs', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.IntegerField(choices=[(0, 'false'), (1, 'true')], default=0)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_tasks', to='tasks.taskings')),
            ],
        ),
    ]
